### ISSUE TITLE
Rename and publish to f-droid please

### ISSUE THREAD

**Issue by edio** [avuton/KeikaiLauncher#6]
I think, request is rather obvious.
But this is just to demonstrate, that there's a demand for this launcher ;)
Thanks for making this fork!

As for the name, I'd suggest to stick to the original naming scheme (as a tribute to the original Hayai launcher) and use something form Japanese, any synonym of _fast_ for example (which is _hayai_). Few options I've got from google translate:
* Keikai (light, nimble)
* Jinsoku (swift)
* Kuikku (quick)

An ideal option would Japanese for _faster_, but unfortunately, it doesn't translate to a signle word.

**Comment by thereiskeks** [comment]
I approve. The names are nice. We should use them.

Is there a possibility in GitHub or fDroid to mark the original launcher as obsolete or sth? As fdroid doesn't have any comments or ratings, the users won't know which one to download.

**Comment by avuton** [comment]
Thanks for the issue, I was kinda waiting for outside interest to work towards entry to F-Droid. Lack of feedback and complacency (it's good enough for me) has led this project to stall. In this case, it hasn't been a terrible thing. After months of dog fooding with few substantial changes I'm pretty confident in it's stability at this point.

With all that said, I like KeikaiLauncher, but I'm open to suggestions if anyone prefers another name for a limited time. I need to do another audit (I haven't review the code in months now) but I'll try to work on renaming in the next few weeks (the new year?). Soon thereafter, I'll work towards getting it into F-Droid.

**Comment by avuton** [comment]
On second thought, for a variety of reasons, I can't really motivate myself to get this done. If someone wants to do it, you're more than welcome to fork and make it happen.

**Comment by wbrawner** [comment]
I'd love to see this on FDroid. Any new name ideas or is KeikaiLauncher the one? I'd be more than happy to go through the submission process and maintain it up to date

**Comment by avuton** [comment]
Yeah, the biggest problem is I'm not really motivated to change the name or submit to F-Droid, particularly. If you want to submit a PR for the name change, and submit to F-Droid, I'll be happy to do that; be aware that I'm a little picky with regard to PRs.

**Comment by wbrawner** [comment]
Sounds good, will do :)

**Comment by wbrawner** [comment]
Any preference on a new package name? Got started on this but F-Droid requires that the app use a new package name as `com.hayaisoftware.launcher` is already taken

**Comment by avuton** [comment]
Sure, I own anpmech.com, so com.anpmech.[whatever name you guys have decided 👍 ]

**Comment by avuton** [comment]
Cool, I'll fix up the rest. It should all be complete soon. Thanks.

**Comment by avuton** [comment]
Package/app name change complete. On to the next part; F-Droid. If I need to be involved in that, I'll need a couple of weeks, probably.

**Comment by go2null** [comment]
Any update on F-droid packaging?

**Comment by thereiskeks** [comment]
Did anybody do sth? If not I think I will do it.

**Comment by avuton** [comment]
Free free to fork and do it, I'm using it personally, but I don't have time to tend to this anymore.

**Comment by avuton** [comment]
Fixed https://github.com/KeikaiLauncher/KeikaiLauncher/issues/2
